apiVersion: v1
kind: Service
metadata:
  name: ai
spec:
  selector:
    app: ai
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000
  type: {{ .Values.service.type }}
